### ISSUE TITLE
Cannot run without X11

### ISSUE THREAD

**Issue by tpankaj** [karlzipser/kzpy3.2#3]
Currently the code can't run without X11. I'd like to be able to use this code on a remote server without X11 and do my visualizations myself.

**Comment by sauhaardac** [comment]
Currently there is a display argument in the Parameters.py file, setting this up is as simple as going to the display code and prepending it with
```python
if args.display:
```
I'm working on it and will let you know when I'm done (prob a couple minutes)

**Comment by karlzipser** [comment]
did you contact Sauhaarda? He has made a major rewrite of the code

---------------------------------------
Karl Zipser, Ph.D.
Assistant Researcher
Helen Wills Neuroscience Institute,
Berkeley DeepDrive Center & Redwood Center for Theoretical Neuroscience
UC Berkeley
561 Evans hall, MC 3198
Berkeley, CA 94720-3198
. .... ...
